package manager 추가
GDG-SSU/wigo pull request #22
Opened 2016-10-25 13:05 UTC by Akkiros

[glide](https://github.com/Masterminds/glide)라는 패키지 매니저를 추가했습니다.

glide를 `curl https://glide.sh/get | sh` 명령어로 설치한 후 glide.yaml 파일이 있는 폴더에서 `glide install` 하시면  vendor 폴더에 라이브러리들이 설치됩니다.

`go15VENDOREXPERIMENT=1` 설정이 필요하다고 메세지가 나오면 `export go15VENDOREXPERIMENT=1` 을 터미널에서 실행해주면 됩니다. (1.6 부터는 쓸모 없다고 하긴 하던데..)

2016-10-25 13:07 UTC, namyunz requested changes
`glide.lock`은 저장소에 포함될 필요가 있는 파일인가요? 보통 이런 것들은 빼야되는 것 같던데

2016-10-25 13:10 UTC, Akkiros commented
@ny-kim lock 파일을 포함한 것은 설치를 하면 해당 lock 파일에 적힌 버전을 보고 install 하기 때문에 버전 관리의 용도로 추가한 것입니다. 라이브러리를 업데이트 한다면 `glide update`를 하면 lock 파일도 같이 업데이트 되고, 다른 사람들도 `glide install`하면 가장 마지막으로 사용하기로 한 버전(lock에 적힌 버전)을 설치하게 되기 때문에 포함 시키는게 좋습니다.

2016-10-25 13:21 UTC, namyunz approved these changes

2016-10-26 20:35 UTC, Corikachu approved these changes

2016-10-27 00:59 UTC, merged