문서 검색 기능 추가
GDG-SSU/wigo pull request #29
Opened 2016-11-01 15:30 UTC by BangUl-Pro

사용자는 `home` url에서 바로 문서를 검색할 수 있습니다.
`App/Index`에서 정해진 폼(title)을 입력한 뒤 `Submit`버튼을 클릭하면 데이터 베이스의 `document` 테이블에 `Query`를 하게 됩니다. 이후 데이터베이스 에러가 발생하거나 POST 방식으로 접근 했을 때 에러 페이지를 띄워줍니다. 성공적으로 데이터베이스에 접근하여 문서가 존재할 때 `title`, `createdAt`, `content` 정보를 보여주고, 문서가 존재하지 않을 때는 문서 작성 페이지로 넘어갑니다.

![2016-11-02 12 28 54](https://cloud.githubusercontent.com/assets/10896116/19895271/745dbe9e-a093-11e6-999c-0f1c673767b5.png)
![2016-11-02 12 29 13](https://cloud.githubusercontent.com/assets/10896116/19895280/795963f8-a093-11e6-9053-5218a83ee4cf.png)
![2016-11-02 12 29 23](https://cloud.githubusercontent.com/assets/10896116/19895283/7b7d86c8-a093-11e6-898c-96e89dfbcd15.png)
![2016-11-02 12 29 27](https://cloud.githubusercontent.com/assets/10896116/19895284/7ddce95e-a093-11e6-8043-7929fabc27f2.png)

2016-11-02 02:07 UTC, Akkiros requested changes

2016-11-02 02:07 UTC, Akkiros commented on app/controllers/search.go
> +    "wigo/app/routes"
이 부분은 "github.com/GDG-SSU/wigo/app/routes" 로 변경이 필요합니다.
Go의 패키지 관리가 좀 이상하여 go get 으로 GDG-SSU/wigo 레파지토리를 받고, $GOPATH/src/github.com/GDG-SSU/wigo 아래에서 브랜치 따로 파서 작업을 하면 됩니다!

2016-11-02 02:07 UTC, Akkiros commented on app/controllers/search.go
> +            return c.Redirect(routes.Document.Write())
해당하는 문서가 없다면 바로 글 쓰기로 이동하는 것 보다는 없다는걸 알려주는 페이지로 이동을 하고, 해당 페이지에서 글 쓰기 버튼이 있으면 좀 더 좋을 것 같습니다.

2016-11-02 02:07 UTC, Akkiros commented on app/controllers/search.go
> +        app.DB.First(&document, "Title = ?", searchDocumentForm.Title)
Title에 꼭 맞는 것만을 찾으면 검색의 효용성이 조금 떨어지는 것 같습니다.
[sql의 like](http://www.w3schools.com/sql/sql_like.asp)를 사용하면 좀 더 좋을 것 같아요!

2016-11-02 02:07 UTC, Akkiros commented on app/controllers/search.go
> +        app.DB.First(&document, "Title = ?", searchDocumentForm.Title)
그리고 하나만을 가져오는게 아니라 여러개를 가져올 수 있도록 변경하고, 결과값을 리스트로 보여주는 것도 좋을 것 같습니다.

2016-11-02 02:07 UTC, Akkiros commented on app/views/App/Index.html
> +      <input type="text" name="title" autofocus="true" placeholder="Title">
name을 title 보다는 검색이라는 의미에 맞게 변경되면 좋을 것 같아요.

2016-11-02 02:08 UTC, namyunz requested changes

2016-11-02 02:08 UTC, namyunz commented on app/controllers/search.go
> +        app.DB.First(&document, "Title = ?", searchDocumentForm.Title)
검색 같은 기능을 처리할 때는 쿼리 구문에 와일드 카드를 넣어서 처리하는 것이 좋습니다. 그래야 긴 길이의 제목을 갖는 문서라도 사용자가 손쉽게 찾을 수 있겠죠? 예를 들어 _DevFest 2016_이라는 제목을 가지는 문서가 있을 때 사용자는 _Dev_라는 단어만 알고있어도 찾을 수 있어야합니다.

문제는 그렇게되면 _DevFest 2015_도 검색 결과로 나와야하고 _DEVIEW_도 검색 결과로 나올 수 있겠죠. 이런 상황을 어떻게 처리할지는 고민해보세요.

2016-11-02 02:08 UTC, namyunz commented on app/controllers/search.go
> +func (c Document) Search() revel.Result {
이러한 함수 정의는 `Document` 클래스의 멤버 함수로 `Search`를 선언하겠다는 의미입니다. 가능하다면 파일 이름과 클래스 이름은 동일하게 작성해주세요.

2016-11-02 02:08 UTC, namyunz commented on app/views/App/Index.html
> +      <input type="text" name="title" autofocus="true" placeholder="Title">
인덱스 페이지에서 검색 질의 입력 폼에 굳이 `autofocus` 속성은 안넣어도 됩니다.

2016-11-02 02:08 UTC, namyunz commented on .gitignore
> +#intelliJ
IDE에 대한 gitignore 설정은 본인 작업 환경에 있는 `gitignore_global` 파일에 선언해주세요. [참고](https://help.github.com/articles/ignoring-files/) 

저장소에 있는 `.gitignore` 파일에 선언해도 되긴하지만 개인적으로 선호하지 않는 방식이라 😶

2016-11-02 04:13 UTC, BangUl-Pro commented on app/controllers/search.go
> +    "wigo/app/routes"
아 저런 문제가 생기는군요...

2016-11-02 04:15 UTC, BangUl-Pro commented on app/controllers/search.go
> +        app.DB.First(&document, "Title = ?", searchDocumentForm.Title)
음 넵 title + content도 검색가능하게 바꿔보겠습니다.

2016-11-02 04:15 UTC, BangUl-Pro commented on app/controllers/search.go
> +        app.DB.First(&document, "Title = ?", searchDocumentForm.Title)
아 물론 like 사용하면서요!

2016-11-02 04:20 UTC, BangUl-Pro commented on app/views/App/Index.html
> +      <input type="text" name="title" autofocus="true" placeholder="Title">
네이버나 구글 같은 사이트를 봤을 때 검색 질의 입력 폼에 `autofocus` 되어 있어서 편하게 검색할 수 있었던것 같아서 넣었습니다.

2016-11-02 04:21 UTC, kyoodong commented on .gitignore
> +#intelliJ
넵 감사합니다 수정하겠습니다.

2016-11-07 08:17 UTC, kyoodong commented on app/controllers/search.go
> +func (c Document) Search() revel.Result {
document.go 에 넣으려고 했는데 코드가 너무 길어지는 것 같습니다.
그래서 controllers/documents 디렉토리를 만들어서 내부 go파일에서 document 클래스를 공유하는 방식으로 하려고 합니다.

2016-11-07 08:19 UTC, BangUl-Pro commented on app/controllers/search.go
> +func (c Document) Search() revel.Result {
덧붙이자면 디렉토리로 관리하게 되었을 때 기존 document.go 파일은 write.go 로 이름이 변경될 것 같습니다. 새로운 document.go 파일은 문서를 보여주는 역할을 담당할 예정입니다.

2016-11-09 09:39 UTC, BangUl-Pro commented
검색 시 `documents` 테이블의 `Title`과 `Content` 중 검색어가 포함된 row의 `id` 와 `title`을 얻어옵니다. 
그리고 `document/search`페이지로 이동합니다. 이 때 검색 결과인 `documents`가 비어있다면 문서 작성 질의 폼이 나타나고, 작성하기 버튼을 클릭하면 `document/write`페이지로 이동합니다.
검색된 문서가 있다면 문서들의 리스트의 `title`을 보여주고, 선택 시 `document`페이지로 이동하여 문서의 모든 정보를 보여줍니다.

![2016-11-09 6 37 15](https://cloud.githubusercontent.com/assets/10896116/20133608/8fe3b8c6-a6ab-11e6-854d-fb1a81f70b0d.png)

![2016-11-09 6 37 41](https://cloud.githubusercontent.com/assets/10896116/20133624/a0f99536-a6ab-11e6-868d-4d18f0c3bc56.png)

2016-11-15 12:57 UTC, namyunz approved these changes

2016-11-16 05:32 UTC, Akkiros approved these changes

2016-11-16 05:35 UTC, merged